### ISSUE TITLE
File Pulse Source Connector Unable to setup

### ISSUE THREAD

**Issue by macteja** [streamthoughts/kafka-connect-file-pulse#24] opened 2020-05-14 19:43 UTC
Hello Team,

I am trying to setup the FilePulseSourceConnector in my environment to test the local files sent to kafka topic, but by following the procedure creating the connector, unfortunately it is not allowing to setup the connector,

Below is the configuration of a connector,

{
"name": "FilePulseSourceConnector",
"config": {
"connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
"tasks.max": "2",
"topic": "connectfilepulse.source",
"fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
"fs.scan.directory.path": "/var/log",
"fs.scan.filters": "worker.log",
"fs.scan.interval.ms": "10",
"FileInputReader": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
"internal.kafka.reporter.topic": "connect-file-pulse-status",
"internal.kafka.reporter.id": "test",
"internal.kafka.reporter.cluster.bootstrap.servers": "testserver:1234",
"fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanPolicy",
"task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileReader"
}
}

Errors are below,
Connector configuration is invalid and contains the following 3 error(s):
Invalid value io.streamthoughts.kafka.connect.filepulse.reader.RowFileReader for configuration task.reader.class: Class io.streamthoughts.kafka.connect.filepulse.reader.RowFileReader could not be found.
Missing required configuration "internal.kafka.reporter.bootstrap.servers" which has no default value.
Invalid value io.streamthoughts.kafka.connect.filepulse.clean.LogCleanPolicy for configuration fs.cleanup.policy.class: Class io.streamthoughts.kafka.connect.filepulse.clean.LogCleanPolicy could not be found.

Could you please look into the errors and suggest us to move forward to setup the connector.

Thanks
Mac

**Comment by fhussonnois** [comment] 2020-05-15 07:41
Hi @macteja, could you give me the version of the connector you are trying to execute ?
Also, how did you install it (i.e confluent-hub, github tarball release , compile source code) ?

Thanks,

**Comment by macteja** [comment] 2020-05-21 09:51
Hello @fhussonnois 
Thanks for quick reply, now i was able to to start and send local files to kafka topic.
Had one question like, can we take specific file from the path?

Thanks,
Mac

**Comment by fhussonnois** [comment] 2020-05-21 12:37
Hi @macteja, I think the documentation is not very clear about how to filter input files (I will work on the documentation soon).

File Pulse scans the input directory specified through the property `fs.scan.directory.path`. You can configure and even implement a [FileListFilter](https://github.com/streamthoughts/kafka-connect-file-pulse/blob/e1e1685a9af1607862399db0dd0ff8a9feff8642/connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/scanner/local/FileListFilter.java).

Currenlty the connector provides the following built-in filters : 

* `io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.IgnoreHiddenFileListFilter`
* `io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.LastModifiedFileListFilter`
* `io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter`

You can use the `RegexFileListFilter` to only process a specific file.

**Example**

```
fs.scan.filters=io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter
file.filter.regex.pattern=".*myFile\\.csv$"
```

**Comment by macteja** [comment] 2020-05-21 14:34
Thank you @fhussonnois ,

I will try above and let you the output.
One more quick question, Is there any way to connect to remote host/vm to fetch files and ingest to kafka topic near to realtime?

Thanks
Mac

**Comment by fhussonnois** [comment] 2020-05-21 15:13
Unfortunately this is not possible. You should use another solution to retrieve files (e.g rsync, ftp, etc) or you can mount your remote volume to the host running the connector using SAN or NAS.

**Comment by macteja** [comment] 2020-05-21 15:54
@fhussonnois i will look into your possible options & update any.
I have tested the flow for particular one and good with it.
Adding my config here for your review and any one can use this as a sample if they looking.

{
  "name": "FilePulseSource",
  "config": {
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
  "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
  "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
  "tasks.max": "2",
  "topic": "test",
  "fs.scan.directory.path": "/var/log/",
  "fs.scan.interval.ms": "1000",
  "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
  "file.filter.regex.pattern": ".*worker\\.log$",
  "internal.kafka.reporter.bootstrap.servers": "xyz:123",
  "internal.kafka.reporter.topic": "connect-file-pulse-status",
  "internal.kafka.reporter.id": "connect-file-pulse-quickstart",
  "offset.strategy": "name",
  "read.max.wait.ms": "5000"
}
}

One more quick question, does it support multiple destination source path to get different uri files.
Ex:- First source path - /var/log - regexp - .*.log
Second source path - /usr/log - regexp - .*worker.log etc..

Thanks,
Mac

**Comment by macteja** [comment] 2020-05-21 19:03
@fhussonnois could you please help me on fixing below error,
as i am created the connector with above comment config, but connector is in FAILED state, but still task is running fine and sending metrics to kafka topic.

"trace": "java.lang.IllegalStateException: Cannot init again.\n\tat io.streamthoughts.kafka.connect.filepulse.storage.KafkaStateBackingStore.start(KafkaStateBackingStore.java:94)\n\tat io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner.<init>(LocalFileSystemScanner.java:152)\n\tat io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector.start(FilePulseSourceConnector.java:107)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.resume(WorkerConnector.java:131)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:198)\n\tat org.apache.kafka.connect.runtime.Worker.transitionTo(Worker.java:828)\n\tat org.apache.kafka.connect.runtime.Worker.setTargetState(Worker.java:812)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.processTargetStateChanges(DistributedHerder.java:479)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:341)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:245)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n

Please help me on fixing above error.

Thanks you very much for your extreme support.

Mac.

**Comment by fhussonnois** [comment] 2020-05-21 22:20
This actually a known issue. The connector initializes a singleton in the JVM (`KafkaStateBackingStore`) per `internal.kafka.reporter.id` to track the progression of each file. When the connector is stopped properly the  `KafkaStateBackingStore` is closed. 

However, if you don't succed to start the connector at first and the connector crashes abruptly then you will have memory leak. The connector will try to restart the previous  `KafkaStateBackingStore`.

This should not happen in production. To solve that problem during  development you have to restart your Kafka Worker or change the `internal.kafka.reporter.id` property.

**Comment by macteja** [comment] 2020-05-22 05:57
@fhussonnois valuable information and worked exactly as mentioned.
This should not happen in production. It means any other suggestion not to get in to this kind of situation?
Production it is difficult to perform whatever you mentioned 2 tasks as frequently & memory leak can cause of hung the system.

If possible can you update insights about below question,
Does it support multiple source paths to get different uri files.
Ex:- First source path - /var/log - regexp - .*.log
Second source path - /usr/log - regexp - .*worker.log etc..

Thanks Once again.

**Comment by fhussonnois** [comment] 2020-05-22 10:08
The problem should not happen in production because this is due to an exception happening while initializing the connector (but of course, we should 'never say never'). 

Hence, I will work on a fix to reduce the risk of that on the next release.

Regarding your questions, currently you can't configure multiple source paths. You should deploy one connector per input directory.

**Comment by macteja** [comment] 2020-05-22 10:18
Ok.. Thanks @fhussonnois for info & confirming the fix status too.
Yes, got your point, If possible can you take this in next release implementation?

Today i am facing again diff issue like,  connector "state": "RUNNING", but task is not going run and it keeps on "state": "UNASSIGNED", only.

Actually i have paused the connector for some extent and resume the operation, later started state is going UNASSIGNED and not polling the logs to topic as well.
Any suggestions on this.

Mac

**Comment by fhussonnois** [comment] 2020-05-22 22:07
Okay, I think I was able to reproduce the problem. I will push a fix as soon as possible.

**Comment by fhussonnois** [comment] 2020-05-25 08:35
Hi @macteja, the release is available : https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v1.3.0 . You can download the new version from the release page. 

Could you please close this issue if all you problems are resolved.

Thank you.

**Comment by macteja** [comment] 2020-05-26 08:00
Thanks @fhussonnois , for your quick response with fix. appreciate your efforts..

I am installing through below hub command
confluent-hub install streamthoughts/kafka-connect-file-pulse:1.3.0

If possible could you please confirm above will work? & can you update to confluent team to update there page with latest info, so that other can use latest one.

I will test once 1.3.0 version and update the findings with closure on this ticket..

Thanks,
Mac

**Comment by fhussonnois** [comment] 2020-05-26 08:20
Hi @macteja , currently you can't install it via Confluent Hub because the new version is not available yet. I'm still waiting for the confluent team. However, you can download the new version here https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v1.3.0

Then you can use the `confluent-hub` CLI to install the downloaded zip file.

```
$ confluent-hub install --no-prompt streamthoughts-kafka-connect-file-pulse-1.3.0.zip
```

**Closed** 2020-08-03 08:35 UTC
